"""empty message

Revision ID: 545d2d1d2689
Revises: e546900c88de
Create Date: 2024-01-11 23:31:59.271567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545d2d1d2689'
down_revision = 'e546900c88de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('uq_favorites_character_id', type_='unique')
        batch_op.drop_constraint('uq_favorites_planet_id', type_='unique')
        batch_op.drop_constraint('uq_favorites_user_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_favorites_user_id', ['user_id'])
        batch_op.create_unique_constraint('uq_favorites_planet_id', ['planet_id'])
        batch_op.create_unique_constraint('uq_favorites_character_id', ['character_id'])
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
