"""empty message

Revision ID: aeae0f0c4cf6
Revises: 545d2d1d2689
Create Date: 2024-01-11 23:39:47.670988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeae0f0c4cf6'
down_revision = '545d2d1d2689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'character_id'])
        batch_op.create_unique_constraint(None, ['user_id', 'planet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
