"""empty message

Revision ID: e546900c88de
Revises: 26c7db1cd4be
Create Date: 2024-01-11 23:20:20.251556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e546900c88de'
down_revision = '26c7db1cd4be'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_favorites_user_id', ['user_id'])
        batch_op.create_unique_constraint('uq_favorites_planet_id', ['planet_id'])
        batch_op.create_unique_constraint('uq_favorites_character_id', ['character_id'])
        batch_op.drop_constraint('favorites_pkey', type_='primary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_primary_key('favorites_pkey', ['id'])
        batch_op.drop_constraint('uq_favorites_user_id', type_='unique')
        batch_op.drop_constraint('uq_favorites_planet_id', type_='unique')
        batch_op.drop_constraint('uq_favorites_character_id', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
